import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex bg-slate-500 text-white font-bold p-5 justify-around">
          <h1>File Uploader -No Library</h1>
          <ul className="flex items-center gap-x-10">
            <Link href={"/"}>Home</Link>
            <Link href={"/file-upload"}>File Upload</Link>
            <Link href={"/display-file"}>Display File</Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
